-- MySQL Script generated by MySQL Workbench
-- Thu Jul 25 12:36:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easymall
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `easymall`;

-- -----------------------------------------------------
-- Schema easymall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easymall` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
USE `easymall`;

-- -----------------------------------------------------
-- User 'easymalldba'
-- -----------------------------------------------------
DROP USER IF EXISTS `easymalldba`@`localhost`;

CREATE USER IF NOT EXISTS 'easymalldba'@'localhost' IDENTIFIED BY 'easymalldba';

GRANT ALL PRIVILEGES ON easymall.* TO 'easymalldba'@'localhost';
-- -----------------------------------------------------
-- Table `easymall`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easymall`.`user` (
  `id` BIGINT(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` INT NOT NULL,
  `status` INT NOT NULL,
  `created_time` TIMESTAMP NOT NULL,
  `updated_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `easymall`.`user` (`name` ASC);


-- -----------------------------------------------------
-- Table `easymall`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easymall`.`product_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_time` TIMESTAMP NOT NULL,
  `updated_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easymall`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easymall`.`product` (
  `id` BIGINT(16) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `amount` INT NOT NULL,
  `product_category_id` INT NOT NULL,
  `status` INT NOT NULL,
  `created_time` TIMESTAMP NOT NULL,
  `updated_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_product_category`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `easymall`.`product_category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE INDEX `fk_product_product_category_idx` ON `easymall`.`product` (`product_category_id` ASC);

CREATE UNIQUE INDEX `name_UNIQUE` ON `easymall`.`product` (`name` ASC);


-- -----------------------------------------------------
-- Table `easymall`.`shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easymall`.`shopping_cart` (
  `user_id` BIGINT(16) NOT NULL,
  `product_id` BIGINT(16) NOT NULL,
  `unit_price` DECIMAL(9,2) NOT NULL,
  `amount` INT NOT NULL,
  `created_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`user_id`, `product_id`),
  CONSTRAINT `fk_shopping_cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `easymall`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_shopping_cart_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `easymall`.`product` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE INDEX `fk_shopping_cart_user_idx` ON `easymall`.`shopping_cart` (`user_id` ASC);

CREATE INDEX `fk_shopping_cart_product_idx` ON `easymall`.`shopping_cart` (`product_id` ASC);


-- -----------------------------------------------------
-- Table `easymall`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easymall`.`transaction` (
  `id` BIGINT(16) NOT NULL,
  `user_id` BIGINT(16) NOT NULL,
  `payment_amount` DECIMAL(9,2) NOT NULL,
  `created_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_transaction_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `easymall`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE INDEX `fk_transaction_user_idx` ON `easymall`.`transaction` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `easymall`.`transaction_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easymall`.`transaction_details` (
  `transaction_id` BIGINT(16) NOT NULL,
  `user_id` BIGINT(16) NOT NULL,
  `product_id` BIGINT(16) NOT NULL,
  `unit_price` DECIMAL(9,2) NOT NULL,
  `amount` INT NOT NULL,
  `created_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`transaction_id`, `user_id`, `product_id`),
  CONSTRAINT `fk_transaction_details_transaction`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `easymall`.`transaction` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_transaction_details_shopping_cart`
    FOREIGN KEY (`user_id` , `product_id`)
    REFERENCES `easymall`.`shopping_cart` (`user_id` , `product_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE INDEX `fk_transaction_details_transaction_idx` ON `easymall`.`transaction_details` (`transaction_id` ASC);

CREATE INDEX `fk_transaction_details_shopping_cart_idx` ON `easymall`.`transaction_details` (`user_id` ASC, `product_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
